---
abstract: 'Double Linked Lists for Perl'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-DoubleLinked
requires:
  Carp: 0
  Scalar::Util: 0
  namespace::clean: 0.20
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=List-DoubleLinked
  repository: git://github.com/Leont/list-doublelinked.git
version: 0.003
